plugins {
	id 'fabric-loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
	id "com.matthewprenger.cursegradle" version "1.4.0"
	id "com.modrinth.minotaur" version "2.+"
}
apply from: "main.gradle"

// Should exist on all loaders and is loader specific
repositories {
	maven {url "https://modmaven.dev/" }// UnionLib
	maven {url "https://girafi.dk/maven/"}
	maven {url "https://www.cursemaven.com"} //CurseForge
    maven {url "https://repo.spongepowered.org/maven"} // mixin
    maven {url 'https://maven.parchmentmc.org'}//Parchment
    maven {url "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"}//Fuzs Mod Resources
}

dependencies {
	minecraft "com.mojang:minecraft:${project._minecraft_version}"
	mappings loom.layered() {
  		officialMojangMappings()
  		//parchment("org.parchmentmc.data:parchment-"+mappingsVersion+"@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${project._loader_version}"
	modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.1.0"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project._loader_api_version}"

	modImplementation ("com.stereowalker.unionlib:UnionLib:${_minecraft_version}-${_unionlib_version}-${_loader}")

	modCompileOnlyApi ("mezz.jei:jei-${_minecraft_version}-common-api:${_jei_version}")
	modCompileOnlyApi ("mezz.jei:jei-${_minecraft_version}-neoforge-api:${_jei_version}")
	modImplementation ("mezz.jei:jei-${_minecraft_version}-neoforge:${_jei_version}")
}
