plugins {
	id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.38'
    id "me.modmuss50.mod-publish-plugin" version "0.7.4"
	id "com.modrinth.minotaur" version "2.+"
}
apply from: "main.gradle"

// Should exist on all loaders and is loader specific
repositories {
	mavenLocal()
	maven {url "https://modmaven.dev/" }// UnionLib
	maven {url "https://www.cursemaven.com"} //CurseForge
    maven {url = "https://repo.spongepowered.org/maven"} // mixin
}

dependencies {
	implementation ("net.neoforged:neoforge:${_loader_version}")
	
	implementation ("com.stereowalker.unionlib:UnionLib:${_minecraft_version}-${_unionlib_version}-${_loader}")

	compileOnly ("mezz.jei:jei-${_minecraft_version}-common-api:${_jei_version}")
	compileOnly ("mezz.jei:jei-${_minecraft_version}-neoforge-api:${_jei_version}")
	implementation ("mezz.jei:jei-${_minecraft_version}-neoforge:${_jei_version}")
}
